Belarusian translation: Thinking in React
reactjs/be.react.dev pull request #10
Opened 2023-06-16 07:18 UTC by zubialevich

Трэба каб нехта паглядзеў свежым вокам)
Я не ўпэўнены наконт "чэкбокс" у перакладзе. Гласарыі прапануюць варыянт "птушка", але я неяк не магу нармальна гэту птушку ў сказ дадаць... Магчыма там трэба нешта кшталту "элемент кіравання птушка"...

2023-06-16 18:14 UTC, belarusaed commented on src/content/learn/thinking-in-react.md
> +2. Знайдзіце іх бліжэйшы агульны бацькоўскі кампанент--гэта кампанент, які знаходзіцца вышэй за іх усіх у іерархіі.
> кампанент--гэта кампанент

Прабелы вакол працяжніка.

2023-06-16 18:14 UTC, belarusaed commented on src/content/learn/thinking-in-react.md
> +Аб апрацоўцы падзей і абнаўленні стану вы можаце прачытаць у раздзеле [Дадаванне інтэрактыўнасці](/learn/adding-interactivity).
> у раздзеле [Дадаванне інтэрактыўнасці](/learn/adding-interactivity)

Па-мойму, лепш

> у раздзеле «[Дадаванне інтэрактыўнасці](/learn/adding-interactivity)»

2023-06-19 07:05 UTC, zubialevich commented on src/content/learn/thinking-in-react.md
> +Стан можна ўявіць як мінімальны набор даных, якія змяняюцца і якія вашай праграме неабходна запомніць. Галоўнае пры рабоце са станам - гэта прытрымлівацца прынцыпу [DRY: Don't Repeat Yourself (бел. н
> Таксама мяне напружвае тое, што ў падобных выпадках кнопка ўваходзіць у спасылку.
Таксама крыху бянтэжыць, што яны так у арыгінале робяць)

2023-06-20 09:24 UTC, belarusaed requested changes
Акрамя гэтага больш заўваг не маю. Мяркую, можна аб’яднаць у main пасля выпраўлення.

2023-06-20 09:24 UTC, belarusaed commented on src/content/learn/thinking-in-react.md
> +Для пачатку вылучыце ўсе кампаненты і падкампаненты на макеце і дайце ім імёны. Калі вы працуеце з дызайнерам, то магчыма, што ён ўжо неяк назваў гэтыя кампаненты. Спытайцеся ў яго!
> ён Ужо

2023-06-20 09:24 UTC, belarusaed commented on src/content/learn/thinking-in-react.md
> +Вы можаце падыходзіць да разбіцця дызайну на кампаненты па-рознаму, асноўваючыся на вашым досведзе:
> разбіцця

Граматычная база такога не ведае. Мабыць лепш «разбівання».

2023-06-20 09:24 UTC, belarusaed commented on src/content/learn/thinking-in-react.md
> +Стан можна ўявіць як мінімальны набор даных, якія змяняюцца і якія вашай праграме неабходна запомніць. Галоўнае пры рабоце са станам — гэта прытрымлівацца прынцыпу [DRY: Don't Repeat Yourself](https:
> (бел.: не паўтарайся).Вызначыце

Няма прабела.

2023-06-21 10:25 UTC, merged