[WIP] Belarusian translation: Start a new React project
reactjs/be.react.dev pull request #11
Opened 2023-06-17 18:12 UTC by vladislavkovaliov

2023-06-17 18:13 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +[//]: <> (TODO: ???)
?

2023-06-17 18:13 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
>  ## Production-grade React frameworks {/*production-grade-react-frameworks*/}
?

2023-06-18 11:24 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
>  ## Production-grade React frameworks {/*production-grade-react-frameworks*/}
Я бы назваў як-небудзь накшталт «React фрэймворкі, гатовыя для выкарыстання ў працоўным асяроддзі»
@zubialevich што думаеш?

2023-06-18 11:58 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Next.js, азнаёмцеся з [падручнікам па Next.js.](https://nextjs.org/learn/foundations/about-nextjs)
Калі вы новы у Next.js, азнаёмцеся з [tutorial Next.js.]?

2023-06-18 11:58 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +[//]: <> (TODO: развіцця або разгортвання?)
deployment - развіцця - разгортвання ?

2023-06-18 11:58 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +[//]: <> (TODO: new feature?)
?

2023-06-18 12:05 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Next.js, азнаёмцеся з [падручнікам па Next.js.](https://nextjs.org/learn/foundations/about-nextjs)
Я бы, мабыць, напісаў
> Калі вы не знаёмыя з Next.js, раім прачытаць іструкцыю па Next.js

Але не ўпэўнены, ці гучыць «раім прачытаць» добра.

Tutorial як інструкцыя ў нас перакладаецца ў Quick Start.

2023-06-18 12:07 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +[//]: <> (TODO: развіцця або разгортвання?)
deployment — разгортванне па гласарыі Microsoft.

2023-06-18 12:09 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +[//]: <> (TODO: new feature?)
Features лепш перакладаць як функцыі ці магчымасці, як па кантэксце лепш.

2023-06-18 12:58 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Next.js, азнаёмцеся з [падручнікам па Next.js.](https://nextjs.org/learn/foundations/about-nextjs)
imho: раім не гучна для мяне

2023-06-18 18:58 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Next.js, азнаёмцеся з [падручнікам па Next.js.](https://nextjs.org/learn/foundations/about-nextjs)
> Калі вы не знаёмыя з Next.js, звярніцеся да іструкцыі па Next.js

Мяркую, так будзе добра.

2023-06-19 06:12 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +title: Пачнанне новы React праект
`Пачнанне`, магчыма тут абдрукоўка.

Магчыма добры варыянт будзе "Пачаць новы праект React"?

2023-06-19 06:13 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы хочаце стварыць новую праграму або новы вэб-сайт цалкам на React, мы рэкамендуем выбраць адзін з фрэймворкаў на базе React, папулярных у абшыны. Фрэймворк забяспечваюць функцыі, якія ў патрэб
"папулярных у абшыны" -> "папулярных у супольнасці"

2023-06-19 06:13 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы хочаце стварыць новую праграму або новы вэб-сайт цалкам на React, мы рэкамендуем выбраць адзін з фрэймворкаў на базе React, папулярных у абшыны. Фрэймворк забяспечваюць функцыі, якія ў патрэб
ФрэймворкІ забяспечваюць функцыі

2023-06-19 06:18 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
>  ## Production-grade React frameworks {/*production-grade-react-frameworks*/}
«Фрэймворкі на базе React, гатовыя для выкарыстання ў працоўным асяроддзі»

2023-06-19 06:27 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) гэта поўны стэк React фрэймворка.** Ён разнабокавы і дазваляе ствараць React програму любога памеру - ад статычнага блога да складанай дынамічнай програмы. Каб ствары
[Next.js](https://nextjs.org/) гэта фул-стэк React фрэймворк.
@belarusaed  што думаеш?

2023-06-19 06:28 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) гэта поўны стэк React фрэймворка.** Ён разнабокавы і дазваляе ствараць React програму любога памеру - ад статычнага блога да складанай дынамічнай програмы. Каб ствары
З яго дапамогай вы можаце ствараць сайты любога памеру ад простага статычнага блога да складанага дынамічнага сайта.

2023-06-19 06:47 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Next.js падтрымліваецца [Vercel](https://vercel.com/). Вы можаце [пачытаць інструкцыю па Next.js](https://nextjs.org/docs/deployment) на любым Node.js або бессерверным хостынгу, або на вашым уласным
Тут здаецца быццам бы два радкі склеіліся. Таму што "[пачытаць інструкцыю па Next.js]" павінны быць вышэй

2023-06-19 06:48 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Next.js падтрымліваецца [Vercel](https://vercel.com/). Вы можаце [пачытаць інструкцыю па Next.js](https://nextjs.org/docs/deployment) на любым Node.js або бессерверным хостынгу, або на вашым уласным
"Вы можаце [пачытаць інструкцыю па Next.js](https://nextjs.org/docs/deployment) на любым Node.js або бессерверным хостынгу, або на вашым уласным серверы." ->

"Вы можаце [разгарнуць Next.js](https://nextjs.org/docs/deployment) на любым бессерверный хостынг, хостынгу з Node.js або на вашым уласным серверы."

2023-06-19 06:49 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Next.js падтрымліваецца [Vercel](https://vercel.com/). Вы можаце [пачытаць інструкцыю па Next.js](https://nextjs.org/docs/deployment) на любым Node.js або бессерверным хостынгу, або на вашым уласным
"[Цалкам статычныя праграма на Next.js](https://nextjs.org/docs/advanced-features/static-html-export) можна разгарнуць на любым статычным хостынгу." ->
"[Цалкам статычную праграму на Next.js](https://nextjs.org/docs/advanced-features/static-html-export) можна разгарнуць на любым статычным хостынгу."

2023-06-19 07:14 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) гэта React фрэймворк з поўным стэкам і ўкладзенай маршрутызацыяй.** Ён дазваляе разбіваць вашу праграму на ўкладзеныя часткі, якія могуць загружаць дадзеныя паралельна і
> у адказ на дэеянні карыстальніка

у адказ на дзеянні карыстальніка

2023-06-19 07:16 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Remix, азнаёмцеся з [інструкцыя па блогу](https://remix.run/docs/en/main/tutorials/blog) (кароткі) і [інструкцыя па праграме](https://remix. run/docs/en/main/tutorials/jokes) (доўгі).
Для знаёмства з Remix вы можаце азнаёміцца з іх інструкцыямі па стварэнні [блога](https://remix.run/docs/ru/main/tutorials/blog) (кароткая) і [праграмы](https://remix.run/docs /ru/main/tutorials/jokes) (доўгая).

2023-06-19 07:18 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Remix падтрымліваецца [Shopify](https://www.shopify.com/). Калі вы ствараеце Remix праект, вам трэба [выбраць мішень разгортванне](https://remix.run/docs/en/main/guides/deployment). Вы можаце разгарн
> Вы можаце разгарнуць Remix праграму на любым Node.js або бессерверным хостынгу

Вы можаце разгарнуць Remix праграму на любым бессерверным хостынгу або хостынгу з Node.js

2023-06-19 07:21 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Remix падтрымліваецца [Shopify](https://www.shopify.com/). Калі вы ствараеце Remix праект, вам трэба [выбраць мішень разгортванне](https://remix.run/docs/en/main/guides/deployment). Вы можаце разгарн
> [выбраць мішень разгортванне]

Тут трэба нешта прыдумаць. У рускім перакладзе пераклалі як 
[выбраць шаблон для разгортвання праграмы]

@belarusaed што думаеш?

2023-06-19 07:23 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Gatsby](https://www.gatsbyjs.com/) гэта React фрэймворк для хуткіх CMS вэб-сайтаў.** У яго багатая экасістэма плагінаў і ўзровень GraphQL даных спрашчаюць інтэграцыю змесціва, API і сэрвісаў на ад
> гэта React фрэймворк для хуткіх CMS вэб-сайтаў

гэта фрэймворк React для стварэння хуткіх сайтаў з падтрымкай CMS

2023-06-19 07:25 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Gatsby](https://www.gatsbyjs.com/) гэта React фрэймворк для хуткіх CMS вэб-сайтаў.** У яго багатая экасістэма плагінаў і ўзровень GraphQL даных спрашчаюць інтэграцыю змесціва, API і сэрвісаў на ад
> У яго багатая экасістэма плагінаў і ўзровень GraphQL даных спрашчаюць інтэграцыю змесціва, API і сэрвісаў на адным вэб-сайце.

Багатая экасістэма плагінаў і слой даных GraphQL спрашчаюць інтэграцыю змесціва, API і сэрвісаў на адным вэб-сайце.

2023-06-19 07:26 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Gatsby, азнаёмцеся з [інструкцыя па Гэтсбі.](https://www.gatsbyjs.com/docs/tutorial/)
Для хуткага знаёмства з Gatsby, азнаёмцеся з яго [інструкцыяй.](https://www.gatsbyjs.com/docs/tutorial/)

2023-06-19 07:29 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +### Маршрутызатар Next.js прыкладанняў {/*nextjs-app-router*/}
> Маршрутызатар Next.js прыкладанняў

Next.js (маршрутызатар праграм)

2023-06-19 07:33 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Маршрутызатар Next.js прыкладанняў](https://beta.nextjs.org/docs/getting-started) гэта рэдызайн запуску Next.js API, які выконвае бачанне архітэктуры поўнага стэка React каманды.** Гэта дазваляе в
> гэта рэдызайн запуску Next.js API, які выконвае бачанне архітэктуры поўнага стэка React каманды.

— гэта абноўлены API Next.js, які адпавядае таму, як каманда React бачыць архітэктуру фулстэк-праграм сёння.

2023-06-19 07:34 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Маршрутызатар Next.js прыкладанняў](https://beta.nextjs.org/docs/getting-started) гэта рэдызайн запуску Next.js API, які выконвае бачанне архітэктуры поўнага стэка React каманды.** Гэта дазваляе в
> Гэта дазваляе вам атрымліваць дадзеныя ў сінхронных кампанентах, якія працуюць на серверы або нават падчас зборкі.

Маршрутызатар дазваляе загружаць даныя ў асінхронных кампанентах на серверы або нават падчас зборкі.

2023-06-19 07:34 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Маршрутызатар Next.js прыкладанняў **у цяперашні час знаходзіцца ў бэта-версіі і пакуль не рэкамендуецца для вытворчасці** (па стане на сакавік 2023 году). Каб паэксперыментаваць з ім у існуючым прае
> Маршрутызатар Next.js прыкладанняў

Маршрутызатар праграм Next.js

2023-06-19 10:58 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Remix, азнаёмцеся з [інструкцыя па блогу](https://remix.run/docs/en/main/tutorials/blog) (кароткі) і [інструкцыя па праграме](https://remix. run/docs/en/main/tutorials/jokes) (доўгі).
точно на /ru/?

2023-06-19 12:16 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Remix, азнаёмцеся з [інструкцыя па блогу](https://remix.run/docs/en/main/tutorials/blog) (кароткі) і [інструкцыя па праграме](https://remix. run/docs/en/main/tutorials/jokes) (доўгі).
Дакладна, не заўважыў) Лепш на англійскую (або /be/?) версію )

2023-06-20 07:02 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) гэта ўніверсальны стэк React фрэймворка.** Ён разнабокавы і дазваляе ствараць React програму любога памеру - ад статычнага блога да складанай дынамічнай програмы. Каб
> гэта ўніверсальны стэк React фрэймворка

Я ўзяў слова ўніверсальны з наступнага сказа, каб аблегчыць яго. Але ўсё яшчэ трэба перакласці full-stack. Я не ведаю як гэта добра перакласці, магчыма "фулстэк" будзе гучаць нармальна? Што думаеце? 

**[Next.js](https://nextjs.org/) гэта ўніверсальны фулстэк React фрэймворк.**

2023-06-20 07:03 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js](https://nextjs.org/) гэта ўніверсальны стэк React фрэймворка.** Ён разнабокавы і дазваляе ствараць React програму любога памеру - ад статычнага блога да складанай дынамічнай програмы. Каб
> Ён разнабокавы і дазваляе ствараць React програму любога памеру - ад статычнага блога да складанай дынамічнай програмы.

З яго дапамогай вы можаце ствараць сайты любога памеру ад простага статычнага блога да складанага дынамічнага сайта.

2023-06-20 07:04 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Next.js падтрымліваецца [Vercel](https://vercel.com/). Вы можаце [разгарнуць Next.js](https://nextjs.org/docs/deployment) на любым бессерверный хостынг, хостынгу з Node.js або на вашым уласным сервер
> на любым бессерверный хостынг

на любым бессерверным хостынгу

2023-06-20 07:05 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) гэта React фрэймворк з ўніверсальным стэкам і ўкладзенай маршрутызацыяй.** Ён дазваляе разбіваць вашу праграму на ўкладзеныя часткі, якія могуць загружаць даныя паралель
> гэта React фрэймворк з ўніверсальным стэкам і ўкладзенай маршрутызацыяй.

гэта фулстэк React фрэймворк з укладзенай маршрутызацыяй.

2023-06-20 07:05 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Для знаёмства з Remix вы можаце азнаёміцца з іх інструкцыямі па стварэнні блога (кароткая) і [праграмы](https://remix.run/docs/ru/main/tutorials/jokes) (доўгая).
Згубілася спасылка на артыкул пра блог: 
[blog tutorial](https://remix.run/docs/en/main/tutorials/blog)

2023-06-20 07:08 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Remix](https://remix.run/) гэта React фрэймворк з ўніверсальным стэкам і ўкладзенай маршрутызацыяй.** Ён дазваляе разбіваць вашу праграму на ўкладзеныя часткі, якія могуць загружаць даныя паралель
> і абнаўляць у адказ на дзеянні карыстальніка

і абнаўляцца у адказ на дзеянні карыстальніка

Таму што там часткі, якія могуць ... абнаўляцца

2023-06-20 07:09 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Для знаёмства з Remix вы можаце азнаёміцца з іх інструкцыямі па стварэнні блога (кароткая) і [праграмы](https://remix.run/docs/ru/main/tutorials/jokes) (доўгая).
> https://remix.run/docs/ru/main/tutorials/jokes

Мая памылка, трэба en версію https://remix.run/docs/en/main/tutorials/jokes

2023-06-20 07:09 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Remix падтрымліваецца [Shopify](https://www.shopify.com/). Калі вы ствараеце Remix праект, вам трэба [выбраць мішень разгортванне](https://remix.run/docs/en/main/guides/deployment). Вы можаце разгарн
> вам трэба [выбраць мішень разгортванне]

вам трэюа [выбраць шаблон для разгортвання праграмы]

Можа неяк так?

2023-06-20 07:10 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Gatsby](https://www.gatsbyjs.com/) гэта фрэймворк React для стварэння хуткіх сайтаў з падтрымкай CMS.** Багатая экасістэма плагінаў і слой даных GraphQL спрашчаюць інтэграцыю змесціва, API і сэрві
> гэта фрэймворк React

гэта React фрэймворк

2023-06-20 07:11 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Gatsby падтрымліваецца [Netlify](https://www.netlify.com/). Вы можаце [разгарнуць цалкам статычны Gatsby сайт](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) на любым статычным хостын
> пераканаецеся што ваш хостынг

пераканайцеся што ваш хостынг

2023-06-20 07:12 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
>  ### Expo (for native apps) {/*expo*/}
Expo (для натыўных праграм)

@belarusaed @vladislavkovaliov Што думаеце?

2023-06-20 07:14 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) гэта React фрэймворк, які дазваляе ствараць універсальныя праграмы для Android, iOS і вэб-праграмы з сапраўды ўласнымі інтэрфейсам.** Ён забяспечвае SDK для [React Native]
> ўласнымі інтэрфейсам

натыўным карыстальніцкім інтэрфейсам

Калі мы дамовімся, што native app/UI - гэта "натыўны")

2023-06-20 07:16 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) гэта React фрэймворк, які дазваляе ствараць універсальныя праграмы для Android, iOS і вэб-праграмы з сапраўды ўласнымі інтэрфейсам.** Ён забяспечвае SDK для [React Native]
> Ён забяспечвае SDK для [React Native](https://reactnative.dev/), што палягчае выкарыстанне натыўных частак.

Ён пастаўляецца разам з SDK для [React Native](https://reactnative.dev/), што палягчае распрацоўку натыўных частак.

2023-06-20 07:16 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Expo падтрымліваецца [Expo (кампаніі)](https://expo.dev/about). Стварэнне праграм з дапамогай Expo бясплатнае, і вы можаце адпраўляць іх у крамы прыкладанняў Google і Apple без абмежаванні. Expo дада
> [Expo (кампаніі)]

[Expo (кампанія)]

2023-06-20 07:18 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Expo падтрымліваецца [Expo (кампаніі)](https://expo.dev/about). Стварэнне праграм з дапамогай Expo бясплатнае, і вы можаце адпраўляць іх у крамы прыкладанняў Google і Apple без абмежаванні. Expo дада
> Стварэнне праграм з дапамогай Expo бясплатнае, і вы можаце адпраўляць іх у крамы прыкладанняў Google і Apple без абмежаванні.

Вы можаце бясплатна ствараць праграмы з дапамогай Expo і дадаваць іх у крамы Google і Apple без абмежаванняў.

2023-06-20 07:22 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Expo падтрымліваецца [Expo (кампаніі)](https://expo.dev/about). Стварэнне праграм з дапамогай Expo бясплатнае, і вы можаце адпраўляць іх у крамы прыкладанняў Google і Apple без абмежаванні. Expo дада
> Expo дадаткова прадастаўляе платныя воблачныя паслугі.

Дадаткова Expo прапануе платныя воблачныя паслугі.

2023-06-20 07:22 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +#### Ці могу я выкарыстоўваць React без фрэймворка? {/*can-i-use-react-without-a-framework*/}
> Ці могу я

Ці магу я

2023-06-20 09:05 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +#### Ці могу я выкарыстоўваць React без фрэймворка? {/*can-i-use-react-without-a-framework*/}
Можа будзе лепш гучаць так: 
Ці можна выкарыстоўваць React без фрэймворка?

2023-06-20 09:06 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Вы можаце выкарыстоўваць React без фрэймворка - як бы вы [выкарыстоўвалі React для часткі вашай старонкі.](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page) **Адна
> Вы можаце выкарыстоўваць React без фрэймворка - як бы вы [выкарыстоўвалі React для часткі вашай старонкі.](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)

React дакладна можна выкарыстоўваць без фрэймворка. Напрыклад, вы можаце [выкарыстоўваць React толькі для пэўнай часткі старонкі.](/learn/add-react-to-an-existing-project#using-react-for-a-part-of-your-existing-page)

2023-06-20 09:28 UTC, belarusaed commented
У апошнім каміце з’явілася папка `.idea`, трэба яе выдаліць

<img width="305" alt="image" src="https://github.com/reactjs/be.react.dev/assets/90352332/03f2880b-ab27-4a7c-985d-e8d08f47ff04">

2023-06-20 09:52 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Нават калі спачатку вам не патрэбна маршрутызацыя або выбарка даных, вы, верагодна, захочаце дадаць для іх некаторыя бібліятэкі. Як ваш JavaScript расце з кожнай новай функцыяй, вам магчыма прыйдзецц
> Нават калі спачатку вам не патрэбна маршрутызацыя або выбарка даных, вы, верагодна, захочаце дадаць для іх некаторыя бібліятэкі.

Нават калі спачатку вам не патрэбна маршрутызацыя або спампоўка даных, вы, верагодна, захочаце пазней дадаць некаторыя бібліятэкі для гэтага.

2023-06-20 09:55 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Нават калі спачатку вам не патрэбна маршрутызацыя або выбарка даных, вы, верагодна, захочаце дадаць для іх некаторыя бібліятэкі. Як ваш JavaScript расце з кожнай новай функцыяй, вам магчыма прыйдзецц
> Як ваш JavaScript расце з кожнай новай функцыяй, вам магчыма прыйдзецца разабрацца, як падзяліць код для кожнага маршруту асобна.

С кожнай новай функцыяй памер вашага JavaScript кода будзе расці і вам давядзецца задумацца аб тым, як падзяляць код для розных маршрутаў.

2023-06-20 10:00 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Нават калі спачатку вам не патрэбна маршрутызацыя або выбарка даных, вы, верагодна, захочаце дадаць для іх некаторыя бібліятэкі. Як ваш JavaScript расце з кожнай новай функцыяй, вам магчыма прыйдзецц
> Па меры таго, як вашыя патрэбы ў выбарцы даных становяцца складанымі, вы, верагодна, сутыкнецеся з вадаспадамі сеткі сервер-кліент, якія робяць вашу праграму вельмі павольнай.

Па меры таго, як ваша праграма будзе спампоўваць усё больш даных, вы можаце сутыкнуцца з каскаднымі запытамі, якія запаволяць вашу праграму.

2023-06-20 10:05 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Нават калі спачатку вам не патрэбна маршрутызацыя або выбарка даных, вы, верагодна, захочаце дадаць для іх некаторыя бібліятэкі. Як ваш JavaScript расце з кожнай новай функцыяй, вам магчыма прыйдзецц
> Змяніць налады для выканання часткі вашага кода на серверы або падчас зборкі можа быць вельмі складана.

Змяніць налады вялікага праекту так, каб запускаць код на серверы або падчас зборкі, можа аказацца складанай задачай.

2023-06-20 10:36 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
>  ### Expo (for native apps) {/*expo*/}
англицизм получается - мне ок)
имхо: мне почему то кажется что native/tutorial/full-stack и тд - лучше оставять оригинальные

2023-06-20 11:38 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +Калі вы новы у Remix, азнаёмцеся з [інструкцыя па блогу](https://remix.run/docs/en/main/tutorials/blog) (кароткі) і [інструкцыя па праграме](https://remix. run/docs/en/main/tutorials/jokes) (доўгі).
en

2023-06-21 06:20 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
>  ### Expo (for native apps) {/*expo*/}
https://be.wikipedia.org/wiki/%D0%9C%D0%B0%D1%88%D1%8B%D0%BD%D0%BD%D1%8B_%D0%BA%D0%BE%D0%B4

У вікіпедыі прыводзяць варыянты машынны код, родны код і натыўны код. Натыўны мне здаецца неяк больш зразумела гучыць (можа справа звычкі) :)

Наконт туторыялаў - будзем карыстацца тым, што прапаноўваюць гласарыі)

2023-06-21 06:26 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
>**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.**

**Гэтыя праблемы не з'яўляюцца спецыфічнымі для React. Вось чаму ў Svelte ёсць SvelteKit, у Vue ёсць Nuxt і гэтак далей.**

2023-06-21 06:28 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і бібліятэкай выбарцы даных.

Каб іх вырашыць, вам давядзецца інтэграваць ваш зборшчык з абранымі бібліятэкамі для маршрутызацыі і атрымання даных.

2023-06-21 07:00 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Нескладана усталявать першапачатковую наладу, але ёсць шмат тонкасці, звязаных з стварэннем праграмы, якая хутка загружаецца, нават калі яна расце з цягам часу.

Зрабіць першасную наладу і прымусіць усё гэта працаваць разам можа аказацца не так складана, але існуе шмат падводных камянёў аб якіх вам прыйдзецца даведацца, каб падтрымліваць прадукцыйнасць праграмы па меры яе росту.

2023-06-21 07:06 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Вы захочаце адправіць мінімальны аб'ём кода прыкладання, але зрабіць гэта за адзін раз кліент-сервер, паралельна з любымі дадзенымі, неабходнымі для старонкі.

Вы захочаце адпраўляць як мага менш кода, але зрабіць гэта за адзін раўнд запытаў паміж кліентам і серверам, пры гэтым паралельна загружаючы неабходныя для старонкі даныя.

2023-06-21 07:09 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Верагодна, вы захочаце, каб старонка была інтэрактыўнай яшчэ да запуску кода JavaScript, каб падтрымліваць прагрэсіўнае паляпшэнне.

Верагодна, вы захочаце, каб са старонка можна было працаваць яшчэ да запуску JavaScript кода, каб падтрымліваць прагрэсіўнае паляпшэнне.

2023-06-21 07:11 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Магчыма, вы захочаце стварыць цалкую папку з статычнымі файламі HTML для вашэго маркетынгавых старонак, якія можна размясціць дзе заўгодна і пры гэтым працаваць з адключаным JavaScript.

Магчыма, вам спатрэбіцца дадаць папку статычных HTML файлаў для маркетынгавых старонак, якія могуць працаваць з адключаным на старонцы Javascript.

2023-06-21 07:15 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**Гэтыя праблемы не звязаны з React. Вось чаму ў Svelte ёсць SvelteKit, а у Vue ёсць Nuxt і далей.** Каб самастойна вырашыць гэтыя праблемы, вам спатрэбіцца інтэграваць зборшчык з маршрутызатарам і б
> Стварэнне гэтых магчымасцей самастойна патрабуе сур'ёзнай працы.

Самастойнае стварэнне і падтрымка ўсіх гэтых магчымасцей патрабуе вельмі вялікай і сур'ёзнай працы.

2023-06-21 07:17 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +  // 1. Вы знаходзіцеся на серверы, таму можаце размаўляць са сваім узроўнем дадзеных. API не патрабуецца.
> Вы знаходзіцеся на серверы, таму можаце размаўляць са сваім узроўнем дадзеных. API не патрабуецца.

Вы знаходзіцеся на серверы, таму можаце напрамую звярнуцца да вашай базы даных без запытаў да API.

2023-06-21 07:22 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +  // 2. Дадайце любую колькасць логікі рэндэрынгу. Гэта не павялічыць ваш JavaScript пакет.
@belarusaed @vladislavkovaliov 
Як думаеце, ці дарэчна перакладаць bundle як пакет? Можа ёсць сэнс альбо англіцызм выкарыстоўваць "бандл", або неяк яго "раскрыць"? Напрыклад 

> Гэта не павялічыць памер вашага JavaScript пакета.

Гэта не павялічыць памер вашага JavaScript кода, які будзе адпраўлены кліенту ў браўзер.

2023-06-21 07:23 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +  // 3. Перадайце дадзеныя кампанентам, якія будуць працаваць у браўзеры.
> Перадайце дадзеныя кампанентам, якія будуць працаваць у браўзеры.

Перадайце даныя далей кампанентам, якія будуць запускацца ў браўзеры.

2023-06-21 07:24 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Маршрутызатар прыкладанняў Next.js таксама інтэгруе [атрыманне даных з Suspense](/blog/2022/03/29/react-v18#suspense-in-data-frameworks). Гэта дазваляе вам вызначаць стан загрузкі (напрыклад, запаўня
> Маршрутызатар прыкладанняў Next.js таксама інтэгруе [атрыманне даных з Suspense]

Маршрутызатар праграм Next.js таксама падтрымлівае [атрыманне даных з затрымкай (Suspense)]

2023-06-21 07:27 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Маршрутызатар прыкладанняў Next.js таксама інтэгруе [атрыманне даных з Suspense](/blog/2022/03/29/react-v18#suspense-in-data-frameworks). Гэта дазваляе вам вызначаць стан загрузкі (напрыклад, запаўня
> Гэта дазваляе вам вызначаць стан загрузкі (напрыклад, запаўняльнік шкілета) для розных частак вашага карыстальніцкага інтэрфейсу непасрэдна ў вашым дрэве React:

Так вы можаце задаць стан розных частак вашай праграмы пры загрузцы (напрыклад, паказаць заглушкі) непасрэдна ў вашым дрэве React:

2023-06-23 10:35 UTC, vladislavkovaliov commented on src/content/learn/start-a-new-react-project.md
> +  // 2. Дадайце любую колькасць логікі рэндэрынгу. Гэта не павялічыць ваш JavaScript пакет.
я за бандл

2023-06-24 19:15 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +Маршрутызатар Next.js прыкладанняў **у цяперашні час знаходзіцца ў бэта-версіі і пакуль не рэкамендуецца для вытворчасці** (па стане на сакавік 2023 году). Каб паэксперыментаваць з ім у існуючым прае
> Next.js's App Router

Зусім не ўяўляю як гэта называць, я бы так і пакінуў. Тут бо app router ён не таму што роўціць праграму, а таму што так называецца дырэкторыя ў праекце. У Next цяпер два роўтэры: стары pages router і новы app router, называюцца так таму што першы базуецца на файлах у `pages/`, другі на файлах у `app/` адпаведна: 
<img width="282" alt="image" src="https://github.com/reactjs/be.react.dev/assets/90352332/4128e62f-a17a-43f4-bf8d-34a0e6243f01">
https://nextjs.org/docs/app/building-your-application/routing#the-app-router

2023-06-24 20:07 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +  // 2. Дадайце любую колькасць логікі рэндэрынгу. Гэта не павялічыць ваш JavaScript пакет.
Мне суб’ектыўна болей падабаецца пакет. Таксама ў Microsoft ёсць падобны пераклад, праўда што яны яго выкарыстоўваюць у кантэксце sales.

2023-06-24 20:19 UTC, belarusaed commented
Выбачаюся, крыху выпаў.

Крыху павыпраўляў дробязяў.

App Router называўся месцамі па-рознаму, назваў яму менавіта App Router пакуль: https://github.com/reactjs/be.react.dev/pull/11#discussion_r1240921822

---

Звяртаю яшчэ раз увагу сюды: https://github.com/reactjs/be.react.dev/pull/11#discussion_r1233360404
> Для знаёмства з [Framework name] вы можаце азнаёміцца з

Нейкая таўталогія.

Таксама я за тое, каб Tutorial перакладаць усё ж як «інструкцыя», як мінімум таму што такое ў нас ужо ў Quick Start.

---

https://github.com/reactjs/be.react.dev/pull/11#discussion_r1240932853

2023-06-26 04:34 UTC, belarusaed requested changes

2023-06-26 04:34 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +Gatsby падтрымліваецца [Netlify](https://www.netlify.com/). Вы можаце [разгарнуць цалкам статычны Gatsby сайт](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting) на любым статычным хостын
> пераканаецеся што ваш хостынг

пераканайцеся што ваш хостынг

2023-06-26 04:34 UTC, belarusaed commented on src/content/learn/start-a-new-react-project.md
> +  // 2. Дадайце любую колькасць логікі рэндэрынгу. Гэта не павялічыць памер вашага JavaScript пакет.
> Гэта не павялічыць памер вашага JavaScript пакет.

Гэта не павялічыць памер вашага JavaScript пакет**а**.

2023-06-26 05:31 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +**[Next.js App Router](https://beta.nextjs.org/docs/getting-started) — гэта абноўлены API Next.js, які адпавядае таму, як каманда React бачыць архітэктуру фулстэк-праграм сёння.** Маршрутызатар дазва
> Маршрутызатар дазваляе загружаць даныя ў асінхронных кампанентах на серверы або нават падчас зборкі.

Ён дазваляе загружаць даныя ў асінхронных кампанентах на серверы або нават падчас зборкі.

(а то не зразумела, што такое Маршрутызатар, бо мы больш не перакладаем App Router)

2023-06-26 05:41 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі вы яшчэ не перакананыя, або ваша праграма мае незвычайныя абмежаванні, якія не абслугоўваюцца добра гэтымі фрэймворкамі, і вы хочаце запусціць сваю ўласную наладу, мы не можам вас спыніць — дзей
Калі мы вас яшчэ не пераканалі або фрэймворкі не рашаюць тую праблему, якая паўстала перад вашай праграмай і вы хочаце стварыць свой уласны фрэймворк - дзейнічайце! Усталюйце `react` і `react-dom` з npm, наладзьце свой уласны працэс зборкі з дапамогай зборшчыка, напрыклад [Vite](https://vitejs.dev/) або [Parcel](https://parceljs.org/), і па меры неабходнасці дадайце ўсе неабходныя інструменты для маршрутызацыі, статычнай генерацыі кода, сервернага рэндэрынгу і гэтак далей.

2023-06-26 05:48 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Калі мы разведалі, як працягваць React удасканальваць, мы зразумелі, што больш цесная інтэграцыя React з фрэймворкамі (у прыватнасці, з маршрутызацыяй, групаваннем і сервернымі тэхналогіямі) — гэта н
Па меры таго як мы развівалі React, мы зразумелі, што лепшая інтэграцыя з фрэймворкамі (асабліва ў пытаннях маршрутызацыі, зборкі і серверных тэхналогій) прынясе найбольшую карысць нашым карыстальнікам. Каманда Next.js пагадзілася ўзаемадзейнічаць з намі ў пошуку, распрацоўцы, інтэграцыі і тэсціраванні перадавых падыходаў, якія не залежаць ад канкрэтнага фрэймворка, напрыклад [серверныя кампаненты React.](/blog/2023/03/22/react-labs-what- we-have-been-working-on-march-2023#react-server-components)

2023-06-26 05:53 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Гэтыя функцыі з кожным днём набліжаюцца да вытворчасці, і мы вялі перамовы з іншымі распрацоўшчыкамі зборшчыкаў і фрэймворкаў аб іх інтэграцыі. Мы спадзяемся, праз год ці два ўсе фрэймворкі, пераліча
Мы працуем над тым, каб новыя магчымасці сталі прыдатнымі для працоўнага асяроддзя як мага хутчэй, і дамаўляемся з распрацоўшчыкамі зборшчыкаў і фрэймворкаў аб іх інтэграцыі. Мы разлічваем, праз год ці два ўсе пералічаныя фрэймворкі будуць поўнасцю падтрымліваць гэтыя магчымасці. (Калі вы распрацоўшчык фрэймворка і хочаце дапамагчы нам у эксперыментах, калі ласка, дайце нам ведаць!)

2023-06-26 05:53 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Next.js App Router **у цяперашні час знаходзіцца ў бэта-версіі і пакуль не рэкамендуецца для вытворчасці** (па стане на сакавік 2023 году). Каб паэксперыментаваць з ім у існуючым праекце Next.js, [пр
> не рэкамендуецца для вытворчасці

не рэкамендуецца для выкарыстання ў працоўным асяроддзі

2023-06-26 05:54 UTC, zubialevich commented on src/content/learn/start-a-new-react-project.md
> +Напрыклад, вы можаце напісаць толькі серверны кампанент React як `async` функцыю, якая чытае з базы даных або з файла. Затым вы можаце перадаваць даныя з яго ў інтэрактыўныя кампаненты:
> Напрыклад, вы можаце напісаць толькі серверны кампанент

Напрыклад, вы можаце напісаць серверны кампанент

2023-06-28 20:13 UTC, belarusaed approved these changes

2023-06-29 07:23 UTC, zubialevich approved these changes

2023-06-29 07:23 UTC, merged