Importing and Exporting Components
reactjs/be.react.dev pull request #12
Opened 2023-06-25 16:41 UTC by belarusaed

2023-06-26 05:56 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Магіяй кампанентаў з’яўляецца іх гатоўнасць да паўторнага выкарыстання: вы можаце стварыць кампанент, які будзе змяшчаць у сабе іншыя кампаненты. Але з павелічэннем колькасці ўкладзеных кампанентаў,
> ў разбванні

ў разбіванні

2023-06-26 05:57 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Магіяй кампанентаў з’яўляецца іх гатоўнасць да паўторнага выкарыстання: вы можаце стварыць кампанент, які будзе змяшчаць у сабе іншыя кампаненты. Але з павелічэннем колькасці ўкладзеных кампанентаў,
> Гэта дазваляе захоўваць вашымі файламі

Гэта дазваляе захоўваць вашы файлы

2023-06-26 06:02 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +2. **Экспартуйце** вашую функцыю з гэтага файла (Выкарыстоўваючы [прадвызначанае](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/export#using_the_default_export) ці [найменнае
> ці [найменнае]

або [найменнае]

2023-06-26 06:02 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +3. **Імпартуйце** кампанент у файл, дзе вы хочаце яго выкарыстоўваць (адпаведна выкарыстоўваючы [прадвызначанае](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/import#importin
> ці [найменнае]

або [найменнае]

2023-06-26 06:03 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +У дадзеным прыкладзе `Profile` і `Gallery` былі вынесеныя з `App.js` у асобны файл `Gallery.js`. Цяпер вы можаце змяніць `App.js`, каб імпартаваць `Gallery` з `Gallery.js`:
каб імпартаваць `Gallery` з файла `Gallery.js`:

Проста ўдакладніць, каб не было блытаніны..

2023-06-26 06:04 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +     - Імпартуе `Gallery` выкарыстоўваючы **прадвызначанае імпартаванне** з `Gallery.js`.
> з `Gallery.js`.

з файла `Gallery.js`.

2023-06-26 06:05 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Вы таксама можаце сутыкнуцца з выпадкамі, калі ў назве файла прапушчаная частка `.js`:
> калі ў назве файла прапушчаная частка

калі ў назве файла прапушчана частка (?)

2023-06-26 06:06 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Абодва варыянты: `'./Gallery.js'` і `'./Gallery'` будуць працаваць з React, хай і першы варыянт бліжэйшы да таго, як працуюць [натыўныя ES модулі](https://developer.mozilla.org/docs/Web/JavaScript/Gu
> будуць працаваць з React,

будуць працаваць у React,

2023-06-26 06:08 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +#### Розніца між прадвызначаным і найменным экспартаваннем {/*default-vs-named-exports*/}
> між

паміж (?) 

Проста для абмеркавання выбару слова "між") Проста мне больш звычна бачыць "паміж")

2023-06-26 06:10 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +У JavsScript ёсць два асноўных спосабы экспартавання: прадвызначанае экспартаванне і найменнае экспартаванне. У нашых прыкладах дагэтуль выкарыстоўвалася толькі прадвызначанае экспартаванне. Але вы м
> але _найменныя_ экспартаванні можна выкарыстоўваць колькі заўгодна

але _найменныя_ экспартаванні можна выкарыстоўваць колькі хочаце разоў

2023-06-26 06:12 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +**Звычайна людзі выкарыстоўваць прадвызначанае экспартаванне, калі файл экспартуе толькі адзін кампанент, і найменныя экспартаванні, калі файл экспартуе некалькі кампанентаў**. Незалежна ад таго, яко
> стылю напісання коду

стылю напісання кода

2023-06-26 06:13 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Каб пазбавіцца патэнцыйнай блытаніны праз розныя варыянты экспартавання, некаторыя людзі, асабліва хто працуюць у камандзе, карыстаюцца толькі адным стылем экспартавання (прадвызначаным ці найменным)
прадвызначаным або найменным

2023-06-26 06:16 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Перанясіце кампанент `Profile` ва ўласны файл `Profile.js`, затым змяніце кампанент `App`, каб ён рэндэрыў абодва кампаненты: `<Profile />` і `<Gallery />` адно пасля іншага.
> адно пасля іншага

можа тут павінна быць "адзін пасля іншага", бо кампаненты мужчынскага роду

2023-06-26 06:16 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Вы можаце выкарыстоўваць для кампанента `Profile` любы стыль экспартавання: прадвызначаны ці найменны, але не забудзьцеся пераканацца, што выкарыстоўваеце адпаведны сінтаксіс у абодвух файлах: `App.j
> прадвызначаны ці найменны

прадвызначаны або найменны

2023-06-26 06:17 UTC, zubialevich requested changes
Выглядае вельмі файна :)

2023-06-26 10:12 UTC, belarusaed commented on src/content/learn/importing-and-exporting-components.md
> +Вы таксама можаце сутыкнуцца з выпадкамі, калі ў назве файла прапушчаная частка `.js`:
Наогул можна абодва варыянты, але пастараюся ўжываць кароткія формы проста для адзінага стылю.

2023-06-26 10:31 UTC, belarusaed commented on src/content/learn/importing-and-exporting-components.md
> +#### Розніца між прадвызначаным і найменным экспартаваннем {/*default-vs-named-exports*/}
Як я бачу, лепей будзе «паміж», «між» — гэта ўжо мая ўласная звычка) Выпраўлю.
<img width="335" alt="image" src="https://github.com/reactjs/be.react.dev/assets/90352332/9c0a4ba0-c6bc-4d38-b1f2-c216574a8999">
<img width="328" alt="image" src="https://github.com/reactjs/be.react.dev/assets/90352332/cbee0408-2d03-4004-b3ab-7d68c41261a4">

2023-06-26 10:41 UTC, belarusaed commented
Тады калі іншых заўваг не будзе, аддаю мержыць у main

2023-06-27 05:49 UTC, zubialevich reviewed
Памылка на выяве: апошні пункт - "прадвызначаЙным"

2023-06-27 05:52 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +У дадзеным прыкладзе ўсе кампаненты існуюць у **файле каранёвага кампанента**, які называецца `App.js`. У [Create React App](https://create-react-app.dev/), вашая праграма змяшчаецца ў `src/App.js`.
Сам у шоку, але не "базуецца", а "базіруецца"

2023-06-27 05:54 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +У JavsScript ёсць два асноўных спосабы экспартавання: прадвызначанае экспартаванне і найменнае экспартаванне. У нашых прыкладах дагэтуль выкарыстоўвалася толькі прадвызначанае экспартаванне. Але вы м
> У JavsScript

У JavAsScript

2023-06-27 06:26 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Калі вы выкарыстоўваеце _прадвызначанае_ імпартаванне, вы можаце выкарыстоўваць любое імя ў `import`. Напрыклад, вы можаце напісаць `import Banana from './Button.js'` і атрымаць усё той жа прадвызнач
> вы можаце выкарыстоўваць любое імя ў `import`.

далей па тэксце кампаненты маюць толькі "назву", таму магчыма тут таксама трэба замяніць на назву?

2023-06-27 06:29 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +Калі вы выкарыстоўваеце _прадвызначанае_ імпартаванне, вы можаце выкарыстоўваць любое імя ў `import`. Напрыклад, вы можаце напісаць `import Banana from './Button.js'` і атрымаць усё той жа прадвызнач
ды ўвогуле. У кампанентаў імёны ці назвы? Таму што я нешта заблытаўся. Зараз перакладаю артыкул пра кампаненты і там таксама трэба вызначыцца - назва ці імя?

У слоўніках імя таксама мае значэнне: 
Назва прадмета, з’явы.
   Расліна альяс вядома пад імем сталетнік.

Таму здаецца, што тут назва кампанента - можа быць імём, так?

2023-06-27 06:42 UTC, belarusaed commented on src/content/learn/importing-and-exporting-components.md
> +У дадзеным прыкладзе ўсе кампаненты існуюць у **файле каранёвага кампанента**, які называецца `App.js`. У [Create React App](https://create-react-app.dev/), вашая праграма змяшчаецца ў `src/App.js`.
Не зусім разумею чаму

2023-06-27 06:43 UTC, belarusaed commented on src/content/learn/importing-and-exporting-components.md
> +Калі вы выкарыстоўваеце _прадвызначанае_ імпартаванне, вы можаце выкарыстоўваць любое імя ў `import`. Напрыклад, вы можаце напісаць `import Banana from './Button.js'` і атрымаць усё той жа прадвызнач
Зраблю назву тут

2023-06-27 10:13 UTC, zubialevich commented on src/content/learn/importing-and-exporting-components.md
> +У дадзеным прыкладзе ўсе кампаненты існуюць у **файле каранёвага кампанента**, які называецца `App.js`. У [Create React App](https://create-react-app.dev/), вашая праграма змяшчаецца ў `src/App.js`.
Ну добра, тады ўсё выглядае добра, давай мержыць)

2023-06-27 10:13 UTC, zubialevich approved these changes

2023-06-27 10:13 UTC, merged