Writing Markup with JSX
reactjs/be.react.dev pull request #14
Opened 2023-06-28 08:55 UTC by belarusaed

2023-06-28 08:57 UTC, belarusaed commented on src/content/learn/writing-markup-with-jsx.md
> +### 3. camelCase <s>для ўсяго</s> амаль для ўсяго! {/*3-camelcase-salls-most-of-the-things*/}
> 3. camelCase <s>для ўсяго</s> амаль для ўсяго!

Яшчэ варыянты:

> 3. camelCase для <s>ўсяго</s> амаль усяго!

> 3. camelCase *амаль* для ўсяго!

2023-06-29 07:21 UTC, zubialevich requested changes
Вылучыў дзе ёсць памылкі друку. Прабач, што сам не выправіў - зараз пад рукой толькі тэлефон і не вельмі зручну :(

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_sidebar" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Sidebar выклікае функцыю isLoggedIn, яны вылучаны
> філяетавым

фіялетавым

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_sidebar" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Sidebar выклікае функцыю isLoggedIn, яны вылучаны
> Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам.

Кампанент React з папярэдняга прыкладу з HTML і JavaScript злучанымі разам.

Можа так будзе меш заблытана?

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_form" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Form змяшчае два апрацоўшчыкі onClick і onSubmit, ян
> Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам.

Кампанент React з папярэдняга прыкладу з HTML і JavaScript злучанымі разам.

Можа так будзе менш заблытана?

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_form" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Form змяшчае два апрацоўшчыкі onClick і onSubmit, ян
> якіх мае проп

я думаў, што пропс - гэта адзіночны лік ад пропсы. Прынамсі такую форму я выкарыстоўваў у іншых месцах

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_form" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Form змяшчае два апрацоўшчыкі onClick і onSubmit, ян
> За імі HTML вылучаныя фіялетавым.

За імі HTML вылучаны фіялетавым. (?)

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Захоўванне логікі рэндэру кнопкі разам з разметкай гарантуе, што яны застануцца сінхранізаванымі пасля зменаў. І наадварот, дэталі, якія не маюць дачынення адныя да іншых, такія, як разметка кнопкі і
> пасля зменаў

пасля змен 
<img width="860" alt="image" src="https://github.com/reactjs/be.react.dev/assets/11157545/30aa0291-a1d8-47e3-97b6-c7575d2674d4">

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +JSX і React — дзве аосбныя рэчы. Яны часта выкарыстоўваюцца разам, але вы *можаце* [выкарыстоўваць іх незалежна](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-a-jsx
> дзве аосбныя рэчы

дзве асобныя рэчы

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +## Канвертаванне HTML у JSX {/*converting-html-to-jsx*/}
Пытанне. Ці не правільна будзе "канверсаванне" ? Я здаецца адчуваю, што гучыць усё правільна, але не магу знайсці доказаў))

Магчыма як варыянт можна скарыстацца: "Пераўтварэнне HTML у JSX". Але тут на твой густ

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Гэта адбываецца таму што JSX стражэйшы за HTML і мае шэраг дадатковых правілаў! Калі вы паспрабуеце чытаць паведамленні пра памылкі вышэй, яны дапамогуць вам выправіць разметку, таксама вы можаце ска
> дадатковых правілаў

дадатковых правіл

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +У большасці выпадкаў React будзе паказваць вам карысныя паведамленні пра памылкі прама на экане. Калі вы захраслі, паспрабуйце з імі азнаёміцца!
> прама на экане

прама на экране

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Каб вяртуць некалькі элементаў у межах аднаго кампанента, **абгарніце іх у адзін агульны тэг**.
> Каб вяртуць

каб вярнуць \ каб вяртаць

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Гэты пусты тэг называецца *[Фрагмент.](/reference/react/Fragment)* Фрагменты дазваляюць вам групаваць рэчы, не пакідаючы слядоў у дрэвы HTML у браўзеры.
> у дрэвы HTML

у HTML дрэвы ?

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +JSX падрабуе, каб усе тэгі былі закрытыя: няпарныя тэгі, такія як `<img>`, ператвараюцца ў `<img />`, і абгортачныя тэгі, такія як `<li>апельсіны`, павінны быць абавязкова закрытымі: `<li>апельсіны</
> JSX падрабуе

JSX патрабуе

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +### 3. camelCase <s>для ўсяго</s> амаль для ўсяго! {/*3-camelcase-salls-most-of-the-things*/}
Мне падабаецца гэты варыянт:

> camelCase для <s>ўсяго</s> амаль усяго!

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Таму ў React шмат якія HTML і SVG атрыбуты напісаныя ў camelCase. Напрыклад, замест `stroke-width` трэба выкарыстошваць `strokeWidth`. Так як `class` — зарэзерваванае слова, у React трэба пісаць `cla
> выкарыстошваць

выкарыстоўваць

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Цяпер вы ведаеце чаму JSX існуе і як выкарыстошваць яго ў кампанентах:
> выкарыстошваць 

выкарыстоўваць

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +* Паведамленні пра памылкі часта будуць падказваць вам накірунак хутчэйшага вырашэння праблемы.
> вам накірунак хутчэйшага

вам кірунак хутчэйшага

2023-06-29 07:21 UTC, zubialevich commented on src/content/learn/writing-markup-with-jsx.md
> +Дадзены HTML быў устаўлены ў кампанент, але ён не з’яўляецца правільным JSX. Выпраўце гэта:
> Выпраўце гэта:

Выправіце гэта:

2023-06-29 19:11 UTC, belarusaed commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_sidebar" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Sidebar выклікае функцыю isLoggedIn, яны вылучаны
Не, там жа з папярэдняга прыкладу HTML і JavaScript, кампанентаў у папярэдніх прыкладах няма.

2023-06-29 19:12 UTC, belarusaed commented on src/content/learn/writing-markup-with-jsx.md
> +<Diagram name="writing_jsx_form" height={330} width={325} alt="Кампанент React з HTML і JavaScript з папярэдняга прыкладу злучанымі разам. Функцыя Form змяшчае два апрацоўшчыкі onClick і onSubmit, ян
Так, пра пропс забыўся

2023-06-29 19:14 UTC, belarusaed commented on src/content/learn/writing-markup-with-jsx.md
> +## Канвертаванне HTML у JSX {/*converting-html-to-jsx*/}
Магчыма і так, але неяк нязвыклае для мяне слова)

Ператварэнне мне ў любым выпадку больш падабаецца, але я проста да яго не дадумаўся

2023-06-30 06:02 UTC, zubialevich approved these changes

2023-06-30 08:12 UTC, merged