passing-props-to-a-component.md
reactjs/be.react.dev pull request #27
Opened 2023-08-23 12:47 UTC by belarusaed

2023-08-23 12:56 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Пропсы, якія можна перадаць у тэг `<img>` прадвызначаныя (ReactDOM адпавядае [стандарту HTML](https://www.w3.org/TR/html52/semantics-embedded-content.html#the-img-element)). Але ва *ўласныя кампанент
> Вось як гэта рабіць!

Можа неяк так:
Вось як гэта зрабіць!

або

Вось як гэта робіцца!

2023-08-23 13:46 UTC, zubialevich requested changes

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +### Крок 1: Перадаць пропсы дачыннаму кампаненту {/*step-1-pass-props-to-the-child-component*/}
> дачыннаму

даччынаму

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Калі падвойныя фігурныя дужкі пасля `person=` вас блытаюць, напамінаем, што [гэта ўсяго толькі аб’екты](/learn/javascript-in-jsx-with-curly-braces#using-double-curlies-css-and-other-objects-in-jsx) ў
> curlies

я здаецца перакладаў гэта як "фігурныя дужкі".

> ўнутры дужак JSX.
унутры фігурных дужак JSX?

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Цяпер вы можаце прачытаць гэтыя пропсы знутры кампанента `Avatar`.
> знутры кампанента

Цяпер вы можаце прачытаць гэтыя пропсы ўнутры кампанента `Avatar`.

або 

Цяпер вы можаце прачытаць гэтыя пропсы ў кампаненце `Avatar`.

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +### Крок 2: прачытайце пропсы знутры дачыннага кампанента {/*step-2-read-props-inside-the-child-component*/}
> дачыннага

даччынага

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +### Крок 2: прачытайце пропсы знутры дачыннага кампанента {/*step-2-read-props-inside-the-child-component*/}
> прачытайце пропсы знутры дачыннага кампанента

Можа лепш так?
прачытайце пропсы ў даччыным кампаненце

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Вы можаце прачытаць гэтыя пропсы, пералічыўшы іх назвы `person, size` цераз коску ўнутры `({` і `})` адразу пасля `function Avatar`. Гэта дазволіць вам выкарыстоўваць іх знутры кода `Avatar`, нібы ян
> Гэта дазволіць вам выкарыстоўваць іх знутры кода `Avatar`, нібы яны пераменныя.

Гэта дазволіць вам выкарыстоўваць іх у `Avatar`, нібы яны пераменныя.

Можа так?

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Пропсы дазваляюць вам успрымаць бацькоўскі і дачынны кампаненты незалежнымі адзін ад аднаго. Напрыклад, вы можаце змяніць пропсы `person` ці `size` унутры кампанента `Profile` нават не задумваючыся а
>дачынны

даччыны

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Пропсы дазваляюць вам успрымаць бацькоўскі і дачынны кампаненты незалежнымі адзін ад аднаго. Напрыклад, вы можаце змяніць пропсы `person` ці `size` унутры кампанента `Profile` нават не задумваючыся а
> не задумваючыся ад тым

Над (ці аб?)

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Звычайна вам не будзе патрэбны сам аб’ект `props`, прасцей будзе разабраць яго на пропсы па адным адразу.
> разабраць яго на пропсы па адным адразу.

можа "разабраць на асобныя пропсы"?

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +## Перадача пропсаў з карыстаннем сінтаксіса разгортвання {/*forwarding-props-with-the-jsx-spread-syntax*/}
> з карыстаннем

з ВЫкарыстаннем

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Няма нічога дрэннага ў тым, каб паўтараць імёны пропсаў — такі код будзе больш зразумелым. Але магчыма з часам вам захочацца зрабіць яго лаканічней. Некаторыя кампаненты перадаюць свае пропсы дачынны
> дачынным

даччыным

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +**Карыстайцеся аператарам разгортвання разумна.** Калі вы пачынаеце выкарыстоўваць яго ў кожным кампаненце, вы штосьці робіце не так. Часта гэта прыкмета таго, што варта раздзяліць кампаненты і перад
>дачынныя

даччыныя

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +## Перадача JSX у якасці дачынных элементаў {/*passing-jsx-as-children*/}
> дачынных

даччыных

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +**Не спрабуйце «змяняць пропсы». **Калі вы хочаце адрэагаваць на ўведзеныя карыстальнікам даныя (напрыклад, змену колера), вам спатрэбіцца «задаць стан». Падрабязней пра гэта вы можаце даведацца на с
> змену колера

змену колерУ

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +* Вы можаце перадаць усе пропсы дачыннаму элементу, скарыстаўшыся сінтаксісам разгортвання: `<Avatar {...props} />`. Але не выкарыстоўвайце яго зашмат!
> дачыннаму

даччынаму

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +* Каб прачытаць пропсы, скарыстайцеся дэстурызацыйным сінтаксісам: `function Avatar({ person, size })`.
> дэстурызацыйным сінтаксісам:

дэструктурызацыйным сінтаксісам

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +* Пропсы нязменны і адлюстроўваюць толькі цяперашні стан: пры кожны рэндары кампанент атрымлівае новую версію пропсаў.
> рэндары 

ці не рэндЭры

2023-08-23 13:46 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +      <h1>Выбітныя навукоўцы</h1>
У іншым артыкуле я карыстаўся словам: "Вучоныя"

2023-08-23 13:46 UTC, zubialevich commented
Паглядзеў палавіну толькі, трэба яшчэ заданні глянуць потым)

2023-08-23 15:08 UTC, belarusaed commented on src/content/learn/passing-props-to-a-component.md
> +      <h1>Выбітныя навукоўцы</h1>
Я арыентаваўся на артыкул «Апісанне UI», там навукоўцы. Зараз прайшоўся хуценька па артыкулах раздзела, там у пераважнай большасці навукоўцы. Трэ будзе прывесці да аднаго, я бы навукоўцаў пакідаў.

2023-08-23 18:39 UTC, belarusaed commented on src/content/learn/passing-props-to-a-component.md
> +      <h1>Выбітныя навукоўцы</h1>
UPD: закінуў праўкі вучоных у навукоўцаў асобным PR: #29

2023-08-24 05:59 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +      <h1>Выбітныя навукоўцы</h1>
Дзякуй, значыць то я не звярнуў увагі)

2023-08-24 06:04 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
>  <Illustration src="/images/docs/illustrations/i_children-prop.png" alt='A puzzle-like Card tile with a slot for "children" pieces like text and Avatar' />
Здаецца тут таксама можна перакласці альт тэкст

2023-08-24 06:07 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +* Каб прачытаць пропсы, скарыстайцеся дэструктурызацыйным сінтаксісам: `function Avatar({ person, size })`.
> скарыстайцеся дэструктурызацыйным сінтаксісам:

скарыстайце дэструктурызацыйны сінтаксіс:

Здаецца няма слова скарыстацца, ёсць скарыстаць

2023-08-24 06:07 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +* Вы можаце перадаць усе пропсы даччынаму элементу, скарыстаўшыся сінтаксісам разгортвання: `<Avatar {...props} />`. Але не выкарыстоўвайце яго зашмат!
> скарыстаўшыся сінтаксісам

скарыстаўшы сінтаксіс

2023-08-24 06:09 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Іншым рашэннем, больш падобныя на папярэднія прыклады, будзе згрупаваць усе даныя пра асобу ў аб’ект і перадаць яго ў якасці аднаго пропса:
> Іншым рашэннем, больш падобныя на папярэднія прыклады,

Іншым рашэннем, больш падобныМ на папярэднія прыклады,

2023-08-24 06:10 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +#### Рэгуляванне памера відарыса пропсам {/*adjust-the-image-size-based-on-a-prop*/}
памерУ

2023-08-24 06:11 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +У дадзеным выпадку `Avatar` атрымлівае памер у лічбах праз пропс `size`, што задае шырыню і вышыню для элемента `<img>`. У дадзеным прыкладзе пропс `size` зададзены `40`. Але калі вы адкрыеце выяву ў
> У дадзеным прыкладзе пропс `size` зададзены `40`.

У дадзеным прыкладзе пропс `size` мае зададзенае (апцыянальнае слова) значэнне `40`.

2023-08-24 06:12 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +У дадзеным выпадку `Avatar` атрымлівае памер у лічбах праз пропс `size`, што задае шырыню і вышыню для элемента `<img>`. У дадзеным прыкладзе пропс `size` зададзены `40`. Але калі вы адкрыеце выяву ў
> Але калі вы адкрыеце выяву

відарыс, каб усюль было адно слова

2023-08-24 06:13 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +У дадзеным выпадку `Avatar` атрымлівае памер у лічбах праз пропс `size`, што задае шырыню і вышыню для элемента `<img>`. У дадзеным прыкладзе пропс `size` зададзены `40`. Але калі вы адкрыеце выяву ў
> якую вы запрашаеце.

вы запытваеце

2023-08-24 06:14 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Змяніце кампанент `Avatar` так, каб запрашваць відарыс найбольш падыходзячага памеру, базуючыся на пропсе `size`. Канкрэтна, калі `size` меней за `90`, перадайце `'s'` («small») замест `'b'` («big»)
> каб запрашваць відарыс

каб запытваць

2023-08-24 06:15 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Змяніце кампанент `Avatar` так, каб запрашваць відарыс найбольш падыходзячага памеру, базуючыся на пропсе `size`. Канкрэтна, калі `size` меней за `90`, перадайце `'s'` («small») замест `'b'` («big»)
> базуючыся

я памятаю мы абмяркоўвалі гэтае слова, але я не памятаю, што мы вырашылі.  Пакідаем без -ір-?

2023-08-24 06:15 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Змяніце кампанент `Avatar` так, каб запрашваць відарыс найбольш падыходзячага памеру, базуючыся на пропсе `size`. Канкрэтна, калі `size` меней за `90`, перадайце `'s'` («small») замест `'b'` («big»)
> і адкрыць выяву ў новай укладцы

адкрыць відарыс

2023-08-24 06:18 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +Вынесіце кампанент `Card` з разметкі ніжэй і скарыстайцеся пропсам `children`, каб перадаваць у яго розную JSX разметку:
> скарыстайцеся пропсам

скарыстайце пропс

2023-08-24 06:20 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +          <p>Аклілу Лема быў выбітным Эфіопскім навукоўцам, хто адкрыў натуральны спосаб лячэння шыстасамоз.</p>
лячэння шыстасамозу??

2023-08-24 06:21 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +        <p>Аклілу Лема быў выбітным Эфіопскім навукоўцам, хто адкрыў натуральны спосаб лячэння шыстасамоз.</p>
шыстасамозу?

2023-08-24 06:21 UTC, zubialevich commented on src/content/learn/passing-props-to-a-component.md
> +        <p>Аклілу Лема быў выбітным Эфіопскім навукоўцам, хто адкрыў натуральны спосаб лячэння шыстасамоз.</p>
шыстасамозу?

2023-08-24 11:39 UTC, belarusaed commented on src/content/learn/passing-props-to-a-component.md
> +Змяніце кампанент `Avatar` так, каб запрашваць відарыс найбольш падыходзячага памеру, базуючыся на пропсе `size`. Канкрэтна, калі `size` меней за `90`, перадайце `'s'` («small») замест `'b'` («big»)
Тут было пра базавацца, пакінулі так.
https://github.com/reactjs/be.react.dev/pull/12#discussion_r1243487321

2023-08-25 07:12 UTC, zubialevich approved these changes

2023-08-25 10:17 UTC, merged