Translation for Keeping components pure
reactjs/be.react.dev pull request #30
Opened 2023-08-25 07:09 UTC by zubialevich

2023-08-25 21:06 UTC, belarusaed requested changes

2023-08-25 21:06 UTC, belarusaed commented on src/content/learn/keeping-components-pure.md
> +Каб выправіць памылку, выдаліце пераменную `currentPerson`. Замест гэтага перадайце ўсю інфармацыю з `Profile` ў `Header` і `Avatar` праз пропсы. Вам трэба будзе дадаць пропс `person` да абодвух камп
> з `Profile` ў `Header`

Пэўна, тое, што варта было б удакладніць у якой-небудзь моўнай даведцы, але я бы запісаў «у» замест «ў». 
Але я ў дадзеным выпадку грунтуюся на суб’ектыўным меркаванні сябра-філолага, што «у» пісьмова скарачаецца пасля менавіта кірылічных галосных, нават калі яно скарочана вымаўляецца (ў прыклад мне прывялі тое, што пасля лічбаў таксама нібы правільна пісаць у: «чатыры ўрны», але «4 урны»).
Таксама ўжо маё суб’ектыўнае: Profile запісваецца з галосным на канцы, але не мае на канцы галоснага гука: пры вымаўленні «у» не скарацілася б, калі б мы запісалі гэта кірыліцай: «Прафайл», тут адназначна было бы «у», а не «ў».

2023-08-25 21:06 UTC, belarusaed commented on src/content/learn/keeping-components-pure.md
> +Дзякуючы гэтаму мутацыя цяпер стала лакальнай, а функцыя рэндэрынга — чыстай. Тым не менш, вы ўсё яшчэ трэба быць асцярожнымі: напрыклад, калі вы паспрабуеце змяніць якія-небудзь з існуючых элементаў
> вы ўсё яшчэ трэба быць асцярожнымі

вам

2023-08-28 05:55 UTC, zubialevich commented on src/content/learn/keeping-components-pure.md
> +Каб выправіць памылку, выдаліце пераменную `currentPerson`. Замест гэтага перадайце ўсю інфармацыю з `Profile` ў `Header` і `Avatar` праз пропсы. Вам трэба будзе дадаць пропс `person` да абодвух камп
Згодны з табою, тут дакладна у) Я быў няўважлівым

2023-08-28 10:24 UTC, belarusaed approved these changes

2023-08-28 15:03 UTC, merged