Пераклад "Using TypeScript"
reactjs/be.react.dev pull request #39
Opened 2023-10-05 09:46 UTC by belarusaed

Нарэшце пераклаў артыкул. Адзінае, на што хацелася б звярнуць увагу, пакінуў пакуль TypeScript Playground як ёсць, бо не прыдумаў, як лепш перакласці. Можна ці падкінуць які добры варыянт, тады выпраўлю, ці пакінуць як ёсць як уласную назву. 

Але ў другім выпадку мне тады не падабаецца як гучыць радок 438: 
> Вы можаце пабачыць прыклады абодвух тыпаў `React.ReactNode` і `React.ReactElement` з праверкай тыпаў у [гэтай TypeScript playground](#).

2023-10-05 11:12 UTC, belarusaed commented
То напісаў тады «тэставая пляцоўка TypeScript»

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +TypeScript — папулярны спосаб дадаць тыпізацыі ў ваш JavaScript код. TypeScript [падтрымлівае JSX](/learn/writing-markup-with-jsx) з каробкі, вы можаце дадаць паўнавартасную падтрымку React для вэб,
> спосаб дадаць тыпізацыі ў ваш

спосаб дадаць тыпізацыю ў ваш

Наколькі я разумею альбо тыпізацыю (адз. лік), або тыпы (мн. лік) пасуе

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
>  ## Installation {/*installation*/}
Не перакладзена

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +1. `dom` мае быць уключаны ў [`lib`](https://www.typescriptlang.org/tsconfig/#lib) (Заўвага: калі значэнне для `lib` не зададзенае, `dom` уключанае па-змаўчанні).
> `dom` мае быць уключаны
> `dom` уключанае

тут трэба род унармаваць

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +1. `dom` мае быць уключаны ў [`lib`](https://www.typescriptlang.org/tsconfig/#lib) (Заўвага: калі значэнне для `lib` не зададзенае, `dom` уключанае па-змаўчанні).
> `dom` уключанае па-змаўчанні

`dom` прадвызначана ўключаны (ці ўключанае, гл. папярэдні каментарый)

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Усе файлы, што змяшчаюць JSX, маюць мець пашырэнне `.tsx`. Гэта спецыфічнае для TypeScript пашырэнне, які дае TypeScript ведаць, што файл змяшчае JSX.
> які дае TypeScript ведаць, што файл змяшчае JSX

можа неяк так:
> якое кажа TypeScript, што файл змяшчае JSX

тут які->якое і "дае ведаць"->"кажа"

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Узяўшы [кампанент `MyButton`](/learn#components) са старонкі «[Хуткі старт](/learn)», мы можам дадаць апісанне тыпа для пропса `title` кнопкі:
> дадаць апісанне тыпа

дадаць апісанне тыпУ.

Здаецца ў гэтым кантэксце гэта неадушаўлённы прадмет

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Тып, якім вы апісваеце пропсы кампанента, можа быць на столькі простым ці складаным, на колькі вам тое патрэбна, але гэта заўсёды мае быць апісанне тыпа аб’екта праз `type` ці `interface`. Вы можаце
> апісанне тыпа аб’екта

апісанне тыпУ аб’екта

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Тып, якім вы апісваеце пропсы кампанента, можа быць на столькі простым ці складаным, на колькі вам тое патрэбна, але гэта заўсёды мае быць апісанне тыпа аб’екта праз `type` ці `interface`. Вы можаце
> [Object Types]

не перакладзена. Мо [Тыпы аб'ектаў]?

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Тып, якім вы апісваеце пропсы кампанента, можа быць на столькі простым ці складаным, на колькі вам тое патрэбна, але гэта заўсёды мае быць апісанне тыпа аб’екта праз `type` ці `interface`. Вы можаце
>апісання пропсаў, якія можа адпавядаць

апісання пропсаў, якія моГУЦЬ адпавядаць

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Апісанні тыпаў у `@types/react` уключае таксама і тыпізацыю ўбудаваных хукаў, таму вы можаце выкарыстоўваць іх у сваіх кампанентах без дадатковай налады. Яны пабудаваныя такім чынам, каб улічваць код
>разбірацца з дробнай самастойнай тыпізацыяй.

я не вельмі разумею ідэю... Можа так будзе зразумелей:

разбірацца з дробнай тыпізацыяй самастойна.

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Для `enabled` будзе вызначаны тып `boolean`, а `setEnabled` будзе прымаць ці `boolean`, ці функцыю, якая вяртае `boolean`. Калі вы хочаце відавочна перадаць тып для вашага стану, вы можаце задаць яго
> прымаць ці `boolean`, ці функцыю

Думаю так будзе стылістычна "прыгажэй":

прымаць або `boolean`, або функцыю

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> + - `interface State` апісвае стан рэд’юсера.
> рэд’юсера

трэба вызначыцца гэта рэд’юсера ці рэд’юсара (як было вышэй)

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> + - `type CounterAction` апісвае розныя дзеянні, якія могуць быць адпраўленыя рэд’юсеру.
> рэд’юсеру

вызначыцца (2)

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Іншым шляхам відавочна задаць тып стану `initialState` будзе перадаць яго непасрэдна `useReducer`:
> Больш відавочным спосабам задаць тып стану

Што думаеш?

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Разам з тым з’яўляецца патрэба выключаць `| null` пры атрыманні значэння. Мы раім мець хук для праверкі падчас выканання, які б выкідаў памылку пры адсутнасці стану:
> Мы раім мець хук для праверкі

ну зусім зразумеў сэнс сказа

Можа так будзе крыху лепш:

Мы раім дадаць у хук праверку, якая будзе падчас выканання правяраць наяўнасць значэння і выкідваць памылку пры яго адсутнасці.

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +// Гэта прочты прыклад, але вы можаце прыдумаць болей складаны аб’ект
> прочты
просты

> болей
больш

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +      <p>Цяперашні аб’ект: {object.kind}</p>
Бягучы аб'ект? (на твой густ)

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +У залежнасці ад вашых пераваг, вы можаце выкарыстоўваць функцыі `*EventHandler` з тыпаў React для забеспячэння тыпізацыі апрацоўшчыкаў падзей прама падчас аб’яўлення:
> У залежнасці ад вашых пераваг

У залежнасці ад вашых пераваг у стылі кода ??

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
> аўтаматычна вызначаны з апрацоўшчыка

як думаеш, ці не тое ж самае:

аўтаматычна вызначаны ў апрацоўшчыку падзей?

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +React таксама прадастаўляе шмат тыпаў падзей. Поўны іх спіс можна знайсці [тут](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b580df54c0819ec9df62b0835a315dd48b8594a9/types/react/index.d.ts
> ён змяшчае [найбольш выкарыстоўваемых падзеях DOM]

ён змяшчае [самыя папулярныя падзеі DOM]

ці неяк так?

2023-10-05 11:49 UTC, zubialevich commented on src/content/learn/typescript.md
> +Калі вы выкарыстоўваеце ўбудаваныя стылі ў React, вы можаце выкарыстоўваць `React.CSSProperties` для апісання аб’екта, перадаваемага ў пропс `style`. Дадзены тып уключае ўсе магчымыя CSS параметры і
> і ёсць добрым

густаўшчына:

і з'яўляецца добрым ...

будзе крыху больш зразумелым

2023-10-05 13:58 UTC, belarusaed commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
Не зразумеў тут думку

2023-10-05 13:59 UTC, belarusaed commented on src/content/learn/typescript.md
> +React таксама прадастаўляе шмат тыпаў падзей. Поўны іх спіс можна знайсці [тут](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b580df54c0819ec9df62b0835a315dd48b8594a9/types/react/index.d.ts
Ну мяне крыху збянтэжыла слова "папулярныя", бо чым вымяраецца папулярнасць і ці ёсць які рэйтынг, але, добра, выпраўлю

2023-10-05 14:57 UTC, zubialevich commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
Думка такая, што "з апрацоўшчыка", гучыць не зразумела. Магчыма, "у апрацоўшчыку падзей" будзе больш зразумела, бо паказвае дзе будзе адбывацца, а не адкуль

2023-10-05 14:59 UTC, zubialevich commented on src/content/learn/typescript.md
> +Разам з тым з’яўляецца патрэба выключаць `| null` пры атрыманні значэння. Мы раім мець хук для праверкі падчас выканання, які б выкідаў памылку пры адсутнасці стану:
"recommendation is to have the hook do" - тут не ідзе гаворка пра дадаць хук, які нешта рабоць, а хутчэй зрабіць так, каб хук рабіў праверку.

Калі б гаворка ішла пра кастамны хук, то было б нешта накшталт "recommendation is to have the hook TO do"

2023-10-06 07:33 UTC, belarusaed commented on src/content/learn/typescript.md
> +Разам з тым з’яўляецца патрэба выключаць `| null` пры атрыманні значэння. Мы раім мець хук для праверкі падчас выканання, які б выкідаў памылку пры адсутнасці стану:
Аааа, зразумеў. Так, сапраўды, штосьці я пратупіў

2023-10-06 07:38 UTC, belarusaed commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
Тады, як па мне, лепей было б так

2023-10-06 07:39 UTC, zubialevich commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
О, так увогуле клас 👍🏻

2023-10-06 13:03 UTC, zubialevich requested changes

2023-10-06 13:03 UTC, zubialevich commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
Засталося толькі гэта пафіксіць і можна мержыць

2023-10-06 13:50 UTC, belarusaed commented on src/content/learn/typescript.md
> +Калі працуеце з падзеямі DOM у React, тып падзеі можа быць аўтаматычна вызначаны з апрацоўшчыка. Але ж, калі вы хочаце вынесці функцыю-апрацоўшчык вонкі, вам давядзецца відавочна ўказаць тып падзеі.
Ааа, халера, каміт зрабіў, але запушыць забыў)

2023-10-07 11:12 UTC, merged