Убудаваныя хукі
reactjs/be.react.dev pull request #41
Opened 2023-10-13 19:52 UTC by belarusaed

2023-10-13 19:57 UTC, belarusaed commented
Трэба паглядзець, ці нармальна з тэрміналогіяй. Рэфы падглядзеў у ru/uk перакладах, там так пішуць, то спачатку скраў ідэю там. Але я не ўпэўнены, што мне гэта падабаецца, можа лепей нармальна перакласці і назваць спасылкамі, так, напрыклад, у польскім перакладзе. Пэўна, мне трэба меркаванне.

2023-10-14 10:18 UTC, zubialevich requested changes

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Для аптымізацыі прадукцыйнасці пры перарэндэрынгу часта прапускаюць выкананне непатрэбнай працы. напрыклад, вы можаце сказаць React каб выкарыстоўваў кэшаваныя вынікі вылічэнняў ці прапусціць перарэн
> напрыклад, вы

Напрыклад, вы

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Для аптымізацыі прадукцыйнасці пры перарэндэрынгу часта прапускаюць выкананне непатрэбнай працы. напрыклад, вы можаце сказаць React каб выкарыстоўваў кэшаваныя вынікі вылічэнняў ці прапусціць перарэн
> вы можаце сказаць React каб выкарыстоўваў кэшаваныя вынікі вылічэнняў ці прапусціць перарэндэрынг, калі даныя не змяніліся ад папярэдняга рэндэрынгу.

вы можаце сказаць React выкарыстоўваць кэшаваныя вынікі вылічэнняў або прапусціць перарэндэрынг, калі даныя не змяніліся з моманту папярэдняга рэндэрынгу.

Можа неяк так?

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Кадб прапусціць вылічэнні і непатрэбны перарэндэрынг, выкарыстоўвайце наступныя хукі:
> Кадб

Каб

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
> рэрэндэрынг

да гэтага быў перарэндэрынг.

Дарэчы, а як мы ў іншых месцах пісалі? Рэ ці Пера?

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
> сінхроныя

сінхронныя (дзве Н)

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
> якія не маюць блакаваць

якія не павінны (мусяць) блакіраваць ??

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
блакіру́ючы і неблакіру́ючы, бо блакіраваць. Не?

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +- [`useTransition`](/reference/react/useTransition) дазваляе памеціць пераход стану як неблакуючы і дазваляе іншым абнаўленням перарываць яго.
неблакіруючы

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +- [`useDeferredValue`](/reference/react/useDeferredValue) дазваляе адкласці абнаўленне некрытычных часткак інтэрфейса на карысць іншых.
> некрытычных часткак інтэрфейса

некрытычных частак інтэрфейсу

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +*Рэсурсы* — штосьці, да чаго кампаненты могуць атрымаць доступ, не маючы іх як частку ўласнага стану. Напрыклад, кампанент можа прачытаць паведамленне з Promise ці інфармацыю пра тэму з кантэкста.
>паведамленне з Promise ці інфармацыю

паведамленне з Promise АБО інфармацыю

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Для атрымання даных з рэсурса, выкарыстоўвайце наступных хук:
> рэсурса

рэсурсУ

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Для атрымання даных з рэсурса, выкарыстоўвайце наступных хук:
> выкарыстоўвайце наступных хук

выкарыстоўвайце  наступны хук

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +- [`use`](/reference/react/use) дазваляе атрымліваць значэнні з такіх рэсурсаў, як [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) ці [кантэкст](/l
АБО [кантэкст]

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +Гэтыя хукі болей карыстыя аўтарам бібліятэк і не часта выкарыстоўваюцца ў кодзе праграм.
> карыстыя

карысНыя

2023-10-14 10:18 UTC, zubialevich commented on src/content/reference/react/index.md
> +- [`useDebugValue`](/reference/react/useDebugValue) дазваляе наладзіць цэтлік, які React DevTools будзе паказваць для вашага хука.
> цэтлік

Абмяркоўваецца ў  іншым артыкуле

2023-10-14 17:48 UTC, belarusaed commented on src/content/reference/react/index.md
> +*Кантэкст* дазваляе кампаненту [атрымліваць інфармацыю ад далёкіх бацькоўскіх кампанентаў, не перадаючы яе ў якасці пропсаў](/learn/passing-props-to-a-component). Напрыклад, ваш кампанент верхняга ўз
Не, «перадавая» — зусім іншае слова. «Перадаючы» ж — дзеепрыметнік ад «перадаваць», тое, што тут маецца на ўвазе.

2023-10-14 17:50 UTC, belarusaed commented on src/content/reference/react/index.md
> +*Рэфы* дазваляюць кампаненту [ўтрымліваць інфармацыію, якая не выкарыстоўваецца падчас рэндэрынгу](/learn/referencing-values-with-refs), напрыклад: вузлы DOM ці ідэнтыфікатары тайм-аўтаў. У адрозненн
Сапраўды, штосьці я яго прыдумаў. Пакуль напішу пралаз (па сэнсе нібы і добра), але пішы, калі будуць варыянты лепей.

2023-10-14 17:55 UTC, belarusaed commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
А дагэтуль, па-мойму, не было.

2023-10-14 18:02 UTC, belarusaed commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
Ну граматычная база дае як блакіраваць, так і блакаваць. Але, вось, успомніў, што блакіруючы/блакуючы — дзеепрыслоўі, а не прыметнікі, то не ў тым кантэксце ўжытыя. То ці добра яно будзе гучаць як зараз выправіў?

> У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы сінхронныя абнаўленні, што блакуюць карыстальніцкі інтэрфейс, (напрыклад, набор тэксту) і абнаўленні, якія не павінны яго блакаваць (напрыклад, абнаўленне графіка).

2023-10-14 18:25 UTC, belarusaed commented on src/content/reference/react/index.md
> +*Стан* дазваляе кампаненту [«запамінаць» даныя, напрыклад уведзеныя карыстальнікам](/learn/state-a-components-memory). Напрыклад, кампанент з формай можа выкарыстоўваць стан для захавання уведзеных з
З коскай крыху пазней вярнуся

2023-10-16 06:55 UTC, zubialevich requested changes

2023-10-16 06:55 UTC, zubialevich commented on src/content/reference/react/index.md
> +*Рэсурсы* — штосьці, да чаго кампаненты могуць атрымаць доступ, не маючы іх як частку ўласнага стану. Напрыклад, кампанент можа прачытаць паведамленне з Promise або інфармацыю пра тэму з кантэкста.
> пра тэму з кантэкста

пра тэму з кантэкстУ

2023-10-16 06:55 UTC, zubialevich commented on src/content/reference/react/index.md
> +* [`useEffect`](/reference/react/useEffect) падключае кампанент да знейшняй сістэмы.
> знейшняй

знешняй

2023-10-16 06:55 UTC, zubialevich commented on src/content/reference/react/index.md
> +*Кантэкст* дазваляе кампаненту [атрымліваць інфармацыю ад далёкіх бацькоўскіх кампанентаў, не перадаючы яе ў якасці пропсаў](/learn/passing-props-to-a-component). Напрыклад, ваш кампанент верхняга ўз
маеш рацыю, яшчэ не прачнуўся тады)

2023-10-16 06:55 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
Выпраўленне гучыць добра, лепш за дзеепрыслоўі.
Ёсць такое, што абодва словы прысутнічаюць у граматычнай базе, але ў ТСБМ і ТСЛБМ ёсць пакуль толькі адзін варыянт "блакіравАць" (калі нічога не змянілася ў новых выданнях. (у мяне проста ёсць бзік на гэту тэму адносна блакаваць\блакіраваць, то прабач, калі вырашым блакаваць, хай так будзе, але я асабіста прыхільнік блакіраваць)

2023-10-16 06:56 UTC, zubialevich commented
> Трэба паглядзець, ці нармальна з тэрміналогіяй. Рэфы падглядзеў у ru/uk перакладах, там так пішуць, то спачатку скраў ідэю там. Але я не ўпэўнены, што мне гэта падабаецца, можа лепей нармальна перакласці і назваць спасылкамі, так, напрыклад, у польскім перакладзе. Пэўна, мне трэба меркаванне.

Калі ісці шляхам перакладу поўнасцю такіх скарачэнняў, тады варты было б пазбавіцца і ад "пропсаў"... Але яны неяк добра пасуюць тут здаецца, таму мо ёсць сэнс пакінуць і "рэфы"?

2023-10-16 09:14 UTC, belarusaed commented
Ну то тады пакідаем рэфы, мяркую.

2023-10-16 09:19 UTC, belarusaed commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
Ну то мне не так прынцыпова, тады выпраўлю. Пастараюся тады запомніць, што тут суфіксы -ір- не адкідаем яшчэ)

2023-10-16 09:22 UTC, zubialevich commented on src/content/reference/react/index.md
> +Часам бывае, што нельга прапусціць рэрэндэрынг, бо экран мае быць абноўленым. У такім выпадку, вы можаце палепшыць прадукцыйнасць, раздзяліўшы блакуючыя сінхроныя абнаўленні (напрыклад, набор тэксту)
Дзякуй за разуменне, як слоўнікі паправяць, можна будзе абнаўляць

2023-10-16 09:23 UTC, zubialevich approved these changes

2023-10-16 09:23 UTC, merged