Translated useDebugValue
reactjs/be.react.dev pull request #42
Opened 2023-10-14 01:12 UTC by belarusaed

2023-10-14 09:41 UTC, zubialevich requested changes

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` — Хук React, які дазваляе дадаць цэтлік да ўласнага хука ў [React DevTools.](/learn/react-developer-tools)
https://starnik.by/lizabeta/2446

Здаецца, што label мае больш распаўсюджанае значэнне "метка" ці "пазнака", але я не ўпэўнены, што тут не крыху іншы кантэкст. Як думаеш?

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +* **(неабавязковае)** `format` — функцыя фарматавання. Пры даследванні элемента, React DevTools выкліча функцыю фарматавання, перадаўшы ў яе `value` у якасці аргумента, і пакажа адфарматаванае значэн
> Пры даследванні

Пры даследАванні

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +* **(неабавязковае)** `format` — функцыя фарматавання. Пры даследванні элемента, React DevTools выкліча функцыю фарматавання, перадаўшы ў яе `value` у якасці аргумента, і пакажа адфарматаванае значэн
Мы тут https://github.com/reactjs/be.react.dev/blob/eb516eef2dfd7ec03d79ecfa537ca9f234f4a844/src/content/learn/editor-setup.md?plain=1#L14 пагадзіліся на варыянт "фармаціраванне", замест "фарматаванне. Трэба вырашыць, што пакінуць

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +* **(неабавязковае)** `format` — функцыя фарматавання. Пры даследванні элемента, React DevTools выкліча функцыю фарматавання, перадаўшы ў яе `value` у якасці аргумента, і пакажа адфарматаванае значэн
> будзе паказане арыгінальнае

будзе паказанА арыгінальнае

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` не вяртае нічога.
`useDebugValue` нічога не вяртае.

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +#### Вяртае {/*returns*/}
Магчы лепш будзе "Вяртаемыя значэнні"?

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +### Дадаванне цэтліка да ўласнага хука {/*adding-a-label-to-a-custom-hook*/}
Калі вырашым, то магчыма тут будзе не цэтлік, а метка ці яшчэ што

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Выклічце `useDebugValue` на верхнім узроўні вашага [ўласнагахука](/learn/reusing-logic-with-custom-hooks) каб адабразіць прыдатнае да чытання <CodeStep step={1}>значэнне для адладкі</CodeStep> для [R
> [ўласнагахука]

[ўласнага хука]

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Выклічце `useDebugValue` на верхнім узроўні вашага [ўласнагахука](/learn/reusing-logic-with-custom-hooks) каб адабразіць прыдатнае да чытання <CodeStep step={1}>значэнне для адладкі</CodeStep> для [R
> адабразіць

паказаць, адлюстраваць

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Гэта задасць кампаненту, які выклікае `useOnlineStatus` цэтлік `OnlineStatus: "Online"` пры даследванні яго:
> пры даследванні

пры даследАванні

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Гэта задасць кампаненту, які выклікае `useOnlineStatus` цэтлік `OnlineStatus: "Online"` пры даследванні яго:
Цэтлік, ці нешта іншае

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +![Скрыншот React DevTools, у якім паказваецца значэнне для адладкі](/images/docs/react-devtools-usedebugvalue.png)
> Скрыншот 

Можа "здымак экрана", ці проста "здымак"

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Без выкліку `useDebugValue` толькі асноўнае значэнне будзе паказанае (у дадзеным прыкладзе, гэта было б `true`).
Без выкліку `useDebugValue` будзе паказана толькі асноўнае значэнне (у дадзеным прыкладзе — `true`).

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Не дадавайце значэнні для адладкі кожнаму хуку. Гэта найбольш патрэбна для тых хукаў, якія з’яўляюцца часткай агульнай бібліятэкі і маюць складаную ўнутраную структуру даных, якую можа быць складана
> даследваць

даследАваць

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Не дадавайце значэнні для адладкі кожнаму хуку. Гэта найбольш патрэбна для тых хукаў, якія з’яўляюцца часткай агульнай бібліятэкі і маюць складаную ўнутраную структуру даных, якую можа быць складана
> Гэта найбольш патрэбна для тых хукаў, якія з’яўляюцца часткай агульнай бібліятэкі і маюць складаную ўнутраную структуру даных, якую можа быць складана даследваць.

Іх карысна выкарыстоўваць у хуках, што з'яўляюцца часткай агульнай бібліятэкі і ў хуках са складанай унутранай структурай даных, якую можа быць складана інспектаваць (даследаваць).

Можна падумаць, над нейкай такой фармуліроўкай. Асноўная ідэя, што тут 2 выпадка апісана: хукі з агульнай бібліятэкі і хукі са складанай структурай і трэба іх раздзяліць у тэксце

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +### Адтэрміноўка фарматавання значэння для адладкі {/*deferring-formatting-of-a-debug-value*/}
> фарматавання

фірамаціравання?

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Вашая функцыя фарматавання атрымае <CodeStep step={1}>значэнне для адладкі</CodeStep> ў якасці параметра і мае вярнуць <CodeStep step={2}>фарматаванае значэнне</CodeStep>. Калі вы дасладуеце свой кам
> дасладуеце

даследуеце

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу, як кампанент будзе даследвацца. Напрыклад, калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас к
> даследвацца

даследАвацца

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу, як кампанент будзе даследвацца. Напрыклад, калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас к
> Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу

Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі фармаціравання значэння да таго часу

2023-10-14 09:41 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу, як кампанент будзе даследвацца. Напрыклад, калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас к
> калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас кожнага перарэндэрынгу.

калі `date` — экзэмпляр тыпу Date, гэта дазваляе пазбегнуць выканання `toDateString()` падчас кожнага перарэндэрынгу.

2023-10-14 18:06 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` — Хук React, які дазваляе дадаць цэтлік да ўласнага хука ў [React DevTools.](/learn/react-developer-tools)
Так, мяркую, будзе лепей.

2023-10-14 18:09 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` — Хук React, які дазваляе дадаць цэтлік да ўласнага хука ў [React DevTools.](/learn/react-developer-tools)
Ну, каб адпавядаць, лепей замяніць. Мне туды тут болей «пазнака» падабаецца.

2023-10-14 18:11 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +* **(неабавязковае)** `format` — функцыя фарматавання. Пры даследванні элемента, React DevTools выкліча функцыю фарматавання, перадаўшы ў яе `value` у якасці аргумента, і пакажа адфарматаванае значэн
Сапраўды, ужо забываюся пра тое, што было ў PR… Трэба будзе нам скласці ўласную табліцу тэрміналогіі.

2023-10-14 18:14 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +#### Вяртае {/*returns*/}
Гучыць лепей, але мне не зусім падабаецца адсутнасць у граматычнай базе. То трэба падумаць тады, ці варта так рабіць.

2023-10-14 18:18 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу, як кампанент будзе даследвацца. Напрыклад, калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас к
Ці правільна называць гэта экзэмплярам тыпу з пункту гледжання тэрміналогіі? То звычайна гучыць як экзэмпляр класу — тое, пра што ўспомніў падчас перакладу, але не хацелася перагружаць лішнімі тэрмінамі, таму пакінуў так.

2023-10-14 18:19 UTC, belarusaed commented on src/content/reference/react/useDebugValue.md
> +Гэта дазваляе пазбегнуць выканання патэнцыйна складанай логікі да таго часу, як кампанент будзе даследвацца. Напрыклад, калі `date` — экзэмпляр Date, гэта пазбягае выканання `toDateString()` падчас к
Прыдумаў, напішу тады

> калі `date` мае тып Date

2023-10-16 06:59 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` — Хук React, які дазваляе дадаць цэтлік да ўласнага хука ў [React DevTools.](/learn/react-developer-tools)
Згодны, пазнака, добра гучыць

2023-10-16 07:11 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +#### Вяртае {/*returns*/}
Ва ўкраінскім перакладзе падглядзеў варыянт "Вынік" (Результат па-ўкраінску)

2023-10-16 07:12 UTC, zubialevich commented on src/content/reference/react/useDebugValue.md
> +#### Вяртае {/*returns*/}
Але можна пайсці шляхам "больш слоў": Значэнні, якія вяртаюцца

2023-10-16 09:24 UTC, zubialevich approved these changes

2023-10-16 09:24 UTC, merged